name: Run crawl.py every 15 minutes

on:
  # schedule:
  #   - cron: '*/15 * * * *'  # 매 15분마다 실행
  workflow_dispatch:  # 수동으로 실행할 수 있도록 설정

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    container:
      image: wjswls456456/crawing_python:latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "account.json"
          json: ${{ secrets.ACCOUNT_JSON }}  # 올바른 키로 수정


      - name: Create .env file
        run: |
          echo "CALENDAR_ID=${{ secrets.CALENDAR_ID }}" >> .env
          echo "DATABASE_ID=${{ secrets.DATABASE_ID }}" >> .env
          echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}" >> .env


      - name: Run crawl.py
        run: python crawl.py  # crawl.py 실행
