name: Print Environment Variables

on:
  workflow_dispatch:  # 수동으로 실행 가능

jobs:
  print-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print repository secrets
        run: |
          echo "ACCOUNT_JSON=${{ secrets.ACCOUNT_JSON }}"
          echo "CALENDAR_ID=${{ secrets.CALENDAR_ID }}"
          echo "DATABASE_ID=${{ secrets.DATABASE_ID }}"
          echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}"